### ISSUE TITLE
App feed down

### ISSUE THREAD

**Issue by doomedramen** [Squidly271/AppFeed#3]
did that last update 9 mins ago break the feed? I am getting malformed json errors now

**Comment by doomedramen** [comment]
"Last JSON error Recorded: Syntax error"

**Comment by Squidly271** [comment]
Very unlikely but not impossible.   Checks are in place to avoid that.   Can't look though for a couple hours

**Comment by doomedramen** [comment]
No worries, I will try changing my DNS settings shortly but will close.
